name: CI/CD - Build and Push Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: 'Cloud Provider'
        required: true
        type: choice
        options:
          - azure
          - gcp
          - both
        default: 'azure'

env:
  AZURE_CONTAINER_REGISTRY: dharamhcl.azurecr.io # Replace with your ACR name (e.g., myhealthcareacr.azurecr.io)
  GCP_CONTAINER_REGISTRY: gcr.io/my-project-id # Replace with your GCP project ID

jobs:
  build-and-push-acr:
    name: Build and Push to ACR
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'workflow_dispatch' || 
      github.event.inputs.cloud_provider == 'azure' || 
      github.event.inputs.cloud_provider == 'both'
    strategy:
      matrix:
        service:
          - name: patient-service
            context: ./patient-service
            port: 3000
          - name: application-service
            context: ./application-service
            port: 3001
          - name: order-service
            context: ./order-service
            port: 8080
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ matrix.service.name }}
        tags: |
          type=sha,prefix=,format=short
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image - ${{ matrix.service.name }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.context }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.AZURE_CONTAINER_REGISTRY }}/${{ matrix.service.name }}:buildcache
        cache-to: type=registry,ref=${{ env.AZURE_CONTAINER_REGISTRY }}/${{ matrix.service.name }}:buildcache,mode=max
        build-args: |
          BUILD_DATE=${{ github.event.head_commit.timestamp }}
          VCS_REF=${{ github.sha }}
          VERSION=${{ github.ref_name }}

    - name: Scan image for vulnerabilities - ${{ matrix.service.name }}
      if: github.event_name != 'pull_request'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ matrix.service.name }}:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results-${{ matrix.service.name }}.sarif'
      continue-on-error: true

    - name: Upload Trivy scan results to GitHub Security
      if: github.event_name != 'pull_request'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results-${{ matrix.service.name }}.sarif'
      continue-on-error: true

  build-and-push-gcr:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.cloud_provider == 'gcp' || github.event.inputs.cloud_provider == 'both')
    strategy:
      matrix:
        service:
          - name: patient-service
            context: ./patient-service
            port: 3000
          - name: application-service
            context: ./application-service
            port: 3001
          - name: order-service
            context: ./order-service
            port: 8080
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.GCP_CONTAINER_REGISTRY }}/${{ matrix.service.name }}
        tags: |
          type=sha,prefix=,format=short
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image - ${{ matrix.service.name }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.context }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_DATE=${{ github.event.head_commit.timestamp }}
          VCS_REF=${{ github.sha }}
          VERSION=${{ github.ref_name }}

  summary:
    needs: [build-and-push-acr, build-and-push-gcr]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Build Summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "All microservices have been built and pushed" >> $GITHUB_STEP_SUMMARY
        echo "- patient-service" >> $GITHUB_STEP_SUMMARY
        echo "- application-service" >> $GITHUB_STEP_SUMMARY
        echo "- order-service" >> $GITHUB_STEP_SUMMARY